// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/glasses/media_follower_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avikom.Types.Glasses {

  /// <summary>Holder for reflection information generated from avikom/glasses/media_follower_service.proto</summary>
  public static partial class MediaFollowerServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for avikom/glasses/media_follower_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MediaFollowerServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cithdmlrb20vZ2xhc3Nlcy9tZWRpYV9mb2xsb3dlcl9zZXJ2aWNlLnByb3Rv",
            "Eg5hdmlrb20uZ2xhc3NlcxobYXZpa29tL2dlbmVyaWMvcmVzdWx0LnByb3Rv",
            "GiFhdmlrb20vZ2VuZXJpYy9jb250ZW50X3R5cGUucHJvdG8aG2dvb2dsZS9w",
            "cm90b2J1Zi9lbXB0eS5wcm90bxofYXZpa29tL2dsYXNzZXMvbWVkaWFfaW5m",
            "by5wcm90bzLIAQoUTWVkaWFGb2xsb3dlclNlcnZpY2USOwoEUGxheRIZLmF2",
            "aWtvbS5nbGFzc2VzLk1lZGlhSW5mbxoWLmF2aWtvbS5nZW5lcmljLlJlc3Vs",
            "dCIAEjkKBVBhdXNlEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuYXZpa29t",
            "LmdlbmVyaWMuUmVzdWx0IgASOAoEU3RvcBIWLmdvb2dsZS5wcm90b2J1Zi5F",
            "bXB0eRoWLmF2aWtvbS5nZW5lcmljLlJlc3VsdCIAQmwKGGFwcC5hdmlrb20u",
            "dHlwZXMuZ2xhc3Nlc1o5Z2l0bGFiLnViLnVuaS1iaWVsZWZlbGQuZGUvYXZp",
            "a29tL2dvLXR5cGVzL2F2aWtvbS9nbGFzc2VzqgIUQXZpa29tLlR5cGVzLkds",
            "YXNzZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Avikom.Types.Generic.ResultReflection.Descriptor, global::Avikom.Types.Generic.ContentTypeReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Avikom.Types.Glasses.MediaInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
