// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/glasses/remote_control_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avikom.Types.Glasses {

  /// <summary>Holder for reflection information generated from avikom/glasses/remote_control_service.proto</summary>
  public static partial class RemoteControlServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for avikom/glasses/remote_control_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RemoteControlServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cithdmlrb20vZ2xhc3Nlcy9yZW1vdGVfY29udHJvbF9zZXJ2aWNlLnByb3Rv",
            "Eg5hdmlrb20uZ2xhc3NlcxobYXZpa29tL2dlbmVyaWMvcmVzdWx0LnByb3Rv",
            "Ghtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aHGdvb2dsZS9hcGkvYW5u",
            "b3RhdGlvbnMucHJvdG8y8AQKFFJlbW90ZUNvbnRyb2xTZXJ2aWNlEkMKD1No",
            "b3dTdGVwQnJvd3NlchIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmF2aWtv",
            "bS5nZW5lcmljLlJlc3VsdCIAEkMKD0hpZGVTdGVwQnJvd3NlchIWLmdvb2ds",
            "ZS5wcm90b2J1Zi5FbXB0eRoWLmF2aWtvbS5nZW5lcmljLlJlc3VsdCIAEkAK",
            "DFNob3dOZXh0U3RlcBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmF2aWtv",
            "bS5nZW5lcmljLlJlc3VsdCIAEkQKEFNob3dQcmV2aW91c1N0ZXASFi5nb29n",
            "bGUucHJvdG9idWYuRW1wdHkaFi5hdmlrb20uZ2VuZXJpYy5SZXN1bHQiABJB",
            "Cg1TaG93TmV4dE1lZGlhEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuYXZp",
            "a29tLmdlbmVyaWMuUmVzdWx0IgASRQoRU2hvd1ByZXZpb3VzTWVkaWESFi5n",
            "b29nbGUucHJvdG9idWYuRW1wdHkaFi5hdmlrb20uZ2VuZXJpYy5SZXN1bHQi",
            "ABI9CglQbGF5TWVkaWESFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFi5hdmlr",
            "b20uZ2VuZXJpYy5SZXN1bHQiABI+CgpQYXVzZU1lZGlhEhYuZ29vZ2xlLnBy",
            "b3RvYnVmLkVtcHR5GhYuYXZpa29tLmdlbmVyaWMuUmVzdWx0IgASPQoJU3Rv",
            "cE1lZGlhEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuYXZpa29tLmdlbmVy",
            "aWMuUmVzdWx0IgBCbAoYYXBwLmF2aWtvbS50eXBlcy5nbGFzc2VzWjlnaXRs",
            "YWIudWIudW5pLWJpZWxlZmVsZC5kZS9hdmlrb20vZ28tdHlwZXMvYXZpa29t",
            "L2dsYXNzZXOqAhRBdmlrb20uVHlwZXMuR2xhc3Nlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Avikom.Types.Generic.ResultReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
