// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/unity/game_object.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avikom.Types.Unity {

  /// <summary>Holder for reflection information generated from avikom/unity/game_object.proto</summary>
  public static partial class GameObjectReflection {

    #region Descriptor
    /// <summary>File descriptor for avikom/unity/game_object.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameObjectReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5hdmlrb20vdW5pdHkvZ2FtZV9vYmplY3QucHJvdG8SDGF2aWtvbS51bml0",
            "eRocYXZpa29tL3VuaXR5L3RyYW5zcG9zZS5wcm90bxofYXZpa29tL3VuaXR5",
            "L2Fzc2V0X2J1bmRsZS5wcm90byKSAQoKR2FtZU9iamVjdBIMCgRuYW1lGAEg",
            "ASgJEioKCXRyYW5zcG9zZRgCIAEoCzIXLmF2aWtvbS51bml0eS5UcmFuc3Bv",
            "c2USDgoGcHJlZmFiGAMgASgJEg4KBnBhcmVudBgEIAEoCRIqCghjaGlsZHJl",
            "bhgFIAMoCzIYLmF2aWtvbS51bml0eS5HYW1lT2JqZWN0QmYKFmFwcC5hdmlr",
            "b20udHlwZXMudW5pdHlaN2dpdGxhYi51Yi51bmktYmllbGVmZWxkLmRlL2F2",
            "aWtvbS9nby10eXBlcy9hdmlrb20vdW5pdHmqAhJBdmlrb20uVHlwZXMuVW5p",
            "dHliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Avikom.Types.Unity.TransposeReflection.Descriptor, global::Avikom.Types.Unity.AssetBundleReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Avikom.Types.Unity.GameObject), global::Avikom.Types.Unity.GameObject.Parser, new[]{ "Name", "Transpose", "Prefab", "Parent", "Children" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// This message describes a (virtual) object in the current scene.
  /// Properties have been chosen to allo Unity-based peers to create instances from such a message.
  /// However, this message might also be used in contexts where rendering is not necessary.
  /// @author: Alexander Neumann &lt;alneuman@techfak.uni-bielefeld.de>
  /// </summary>
  public sealed partial class GameObject : pb::IMessage<GameObject> {
    private static readonly pb::MessageParser<GameObject> _parser = new pb::MessageParser<GameObject>(() => new GameObject());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameObject> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avikom.Types.Unity.GameObjectReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameObject() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameObject(GameObject other) : this() {
      name_ = other.name_;
      transpose_ = other.transpose_ != null ? other.transpose_.Clone() : null;
      prefab_ = other.prefab_;
      parent_ = other.parent_;
      children_ = other.children_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameObject Clone() {
      return new GameObject(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    //// scene name of the object
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "transpose" field.</summary>
    public const int TransposeFieldNumber = 2;
    private global::Avikom.Types.Unity.Transpose transpose_;
    /// <summary>
    //// the pose of the object relative to its parent
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Avikom.Types.Unity.Transpose Transpose {
      get { return transpose_; }
      set {
        transpose_ = value;
      }
    }

    /// <summary>Field number for the "prefab" field.</summary>
    public const int PrefabFieldNumber = 3;
    private string prefab_ = "";
    /// <summary>
    //// addressable uri of the (audio)visual appearance blueprint/prefab
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Prefab {
      get { return prefab_; }
      set {
        prefab_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parent" field.</summary>
    public const int ParentFieldNumber = 4;
    private string parent_ = "";
    /// <summary>
    //// the parent's name; if not set, an object will be attached to the scene's root or an equivalent group
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Parent {
      get { return parent_; }
      set {
        parent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "children" field.</summary>
    public const int ChildrenFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Avikom.Types.Unity.GameObject> _repeated_children_codec
        = pb::FieldCodec.ForMessage(42, global::Avikom.Types.Unity.GameObject.Parser);
    private readonly pbc::RepeatedField<global::Avikom.Types.Unity.GameObject> children_ = new pbc::RepeatedField<global::Avikom.Types.Unity.GameObject>();
    /// <summary>
    //// a list of nested `GameObjects`; parent will be this object if not stated differently
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Avikom.Types.Unity.GameObject> Children {
      get { return children_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameObject);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameObject other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(Transpose, other.Transpose)) return false;
      if (Prefab != other.Prefab) return false;
      if (Parent != other.Parent) return false;
      if(!children_.Equals(other.children_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (transpose_ != null) hash ^= Transpose.GetHashCode();
      if (Prefab.Length != 0) hash ^= Prefab.GetHashCode();
      if (Parent.Length != 0) hash ^= Parent.GetHashCode();
      hash ^= children_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (transpose_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Transpose);
      }
      if (Prefab.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Prefab);
      }
      if (Parent.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Parent);
      }
      children_.WriteTo(output, _repeated_children_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (transpose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transpose);
      }
      if (Prefab.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Prefab);
      }
      if (Parent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parent);
      }
      size += children_.CalculateSize(_repeated_children_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameObject other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.transpose_ != null) {
        if (transpose_ == null) {
          Transpose = new global::Avikom.Types.Unity.Transpose();
        }
        Transpose.MergeFrom(other.Transpose);
      }
      if (other.Prefab.Length != 0) {
        Prefab = other.Prefab;
      }
      if (other.Parent.Length != 0) {
        Parent = other.Parent;
      }
      children_.Add(other.children_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (transpose_ == null) {
              Transpose = new global::Avikom.Types.Unity.Transpose();
            }
            input.ReadMessage(Transpose);
            break;
          }
          case 26: {
            Prefab = input.ReadString();
            break;
          }
          case 34: {
            Parent = input.ReadString();
            break;
          }
          case 42: {
            children_.AddEntriesFrom(input, _repeated_children_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
