// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/unity/game_object_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avikom.Types.Unity {

  /// <summary>Holder for reflection information generated from avikom/unity/game_object_service.proto</summary>
  public static partial class GameObjectServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for avikom/unity/game_object_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameObjectServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZhdmlrb20vdW5pdHkvZ2FtZV9vYmplY3Rfc2VydmljZS5wcm90bxIMYXZp",
            "a29tLnVuaXR5Ghthdmlrb20vZ2VuZXJpYy9yZXN1bHQucHJvdG8aHmF2aWtv",
            "bS91bml0eS9nYW1lX29iamVjdC5wcm90bxocZ29vZ2xlL2FwaS9hbm5vdGF0",
            "aW9ucy5wcm90bxofYXZpa29tL3VuaXR5L2Fzc2V0X2J1bmRsZS5wcm90byIf",
            "Cg9HYW1lT2JqZWN0UXVlcnkSDAoEbmFtZRgBIAEoCTL0AgoRR2FtZU9iamVj",
            "dFNlcnZpY2USVwoDQWRkEhguYXZpa29tLnVuaXR5LkdhbWVPYmplY3QaFi5h",
            "dmlrb20uZ2VuZXJpYy5SZXN1bHQiHoLT5JMCGCITL3YxL2dsYXNzZXMvb2Jq",
            "ZWN0czoBKhJeCgNTZXQSGC5hdmlrb20udW5pdHkuR2FtZU9iamVjdBoWLmF2",
            "aWtvbS5nZW5lcmljLlJlc3VsdCIlgtPkkwIfIhovdjEvZ2xhc3Nlcy9vYmpl",
            "Y3RzL3tuYW1lfToBKhJiCgNHZXQSHS5hdmlrb20udW5pdHkuR2FtZU9iamVj",
            "dFF1ZXJ5GhguYXZpa29tLnVuaXR5LkdhbWVPYmplY3QiIoLT5JMCHBIaL3Yx",
            "L2dsYXNzZXMvb2JqZWN0cy97bmFtZX0SQgoJQWRkQnVuZGxlEhkuYXZpa29t",
            "LnVuaXR5LkFzc2V0QnVuZGxlGhYuYXZpa29tLmdlbmVyaWMuUmVzdWx0IgAo",
            "AUJmChZhcHAuYXZpa29tLnR5cGVzLnVuaXR5WjdnaXRsYWIudWIudW5pLWJp",
            "ZWxlZmVsZC5kZS9hdmlrb20vZ28tdHlwZXMvYXZpa29tL3VuaXR5qgISQXZp",
            "a29tLlR5cGVzLlVuaXR5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Avikom.Types.Generic.ResultReflection.Descriptor, global::Avikom.Types.Unity.GameObjectReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::Avikom.Types.Unity.AssetBundleReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Avikom.Types.Unity.GameObjectQuery), global::Avikom.Types.Unity.GameObjectQuery.Parser, new[]{ "Name" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// A query message to retrieve information about an object in the scene.
  /// @author: Alexander Neumann &lt;alneuman@techfak.uni-bielefeld.de>
  /// </summary>
  public sealed partial class GameObjectQuery : pb::IMessage<GameObjectQuery> {
    private static readonly pb::MessageParser<GameObjectQuery> _parser = new pb::MessageParser<GameObjectQuery>(() => new GameObjectQuery());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameObjectQuery> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avikom.Types.Unity.GameObjectServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameObjectQuery() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameObjectQuery(GameObjectQuery other) : this() {
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameObjectQuery Clone() {
      return new GameObjectQuery(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    //// unique name of the requested object
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameObjectQuery);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameObjectQuery other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameObjectQuery other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
