// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/unity/task_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avikom.Types.Unity {

  /// <summary>Holder for reflection information generated from avikom/unity/task_config.proto</summary>
  public static partial class TaskConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for avikom/unity/task_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaskConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5hdmlrb20vdW5pdHkvdGFza19jb25maWcucHJvdG8SDGF2aWtvbS51bml0",
            "eRocYXZpa29tL29wdGlvbnMvb3B0aW9ucy5wcm90bxoeYXZpa29tL3VuaXR5",
            "L2dhbWVfb2JqZWN0LnByb3RvIlcKClRhc2tDb25maWcSGQoJdGFza19uYW1l",
            "GAEgASgJQgaKtRgCEAESKAoGYXNzZXRzGAMgAygLMhguYXZpa29tLnVuaXR5",
            "LkdhbWVPYmplY3Q6BIi1GAFCZgoWYXBwLmF2aWtvbS50eXBlcy51bml0eVo3",
            "Z2l0bGFiLnViLnVuaS1iaWVsZWZlbGQuZGUvYXZpa29tL2dvLXR5cGVzL2F2",
            "aWtvbS91bml0eaoCEkF2aWtvbS5UeXBlcy5Vbml0eWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Avikom.Types.Options.OptionsReflection.Descriptor, global::Avikom.Types.Unity.GameObjectReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Avikom.Types.Unity.TaskConfig), global::Avikom.Types.Unity.TaskConfig.Parser, new[]{ "TaskName", "Assets" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// This message describes a task config and contains context-specific objects.
  /// All assets should have a parent that represents their location within a scene.
  /// @author: Alexander Neumann &lt;alneuman@techfak.uni-bielefeld.de>
  /// </summary>
  public sealed partial class TaskConfig : pb::IMessage<TaskConfig> {
    private static readonly pb::MessageParser<TaskConfig> _parser = new pb::MessageParser<TaskConfig>(() => new TaskConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TaskConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avikom.Types.Unity.TaskConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TaskConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TaskConfig(TaskConfig other) : this() {
      taskName_ = other.taskName_;
      assets_ = other.assets_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TaskConfig Clone() {
      return new TaskConfig(this);
    }

    /// <summary>Field number for the "task_name" field.</summary>
    public const int TaskNameFieldNumber = 1;
    private string taskName_ = "";
    /// <summary>
    //// name of the task that is configured
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TaskName {
      get { return taskName_; }
      set {
        taskName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "assets" field.</summary>
    public const int AssetsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Avikom.Types.Unity.GameObject> _repeated_assets_codec
        = pb::FieldCodec.ForMessage(26, global::Avikom.Types.Unity.GameObject.Parser);
    private readonly pbc::RepeatedField<global::Avikom.Types.Unity.GameObject> assets_ = new pbc::RepeatedField<global::Avikom.Types.Unity.GameObject>();
    /// <summary>
    //// a list of assets that represent (virtual) task-specific assets
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Avikom.Types.Unity.GameObject> Assets {
      get { return assets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TaskConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TaskConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaskName != other.TaskName) return false;
      if(!assets_.Equals(other.assets_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TaskName.Length != 0) hash ^= TaskName.GetHashCode();
      hash ^= assets_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TaskName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TaskName);
      }
      assets_.WriteTo(output, _repeated_assets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TaskName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskName);
      }
      size += assets_.CalculateSize(_repeated_assets_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TaskConfig other) {
      if (other == null) {
        return;
      }
      if (other.TaskName.Length != 0) {
        TaskName = other.TaskName;
      }
      assets_.Add(other.assets_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TaskName = input.ReadString();
            break;
          }
          case 26: {
            assets_.AddEntriesFrom(input, _repeated_assets_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
