// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/generic/content_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avikom.Types.Generic {

  /// <summary>Holder for reflection information generated from avikom/generic/content_type.proto</summary>
  public static partial class ContentTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for avikom/generic/content_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ContentTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFhdmlrb20vZ2VuZXJpYy9jb250ZW50X3R5cGUucHJvdG8SDmF2aWtvbS5n",
            "ZW5lcmljKqkBCgtDb250ZW50VHlwZRITCg9DT05URU5UX1VOS05PV04QABIR",
            "Cg1DT05URU5UX0lNQUdFEAESEQoNQ09OVEVOVF9WSURFTxACEhAKDENPTlRF",
            "TlRfVEVYVBADEhEKDUNPTlRFTlRfQVVESU8QBBISCg5DT05URU5UX1ZJU1VB",
            "TBAFEhQKEENPTlRFTlRfRVhURVJOQUwQBhIQCgxDT05URU5UX1NTTUwQB0Js",
            "ChhhcHAuYXZpa29tLnR5cGVzLmdlbmVyaWNaOWdpdGxhYi51Yi51bmktYmll",
            "bGVmZWxkLmRlL2F2aWtvbS9nby10eXBlcy9hdmlrb20vZ2VuZXJpY6oCFEF2",
            "aWtvbS5UeXBlcy5HZW5lcmljYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Avikom.Types.Generic.ContentType), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///*
  /// Defines the type of an Instruction.
  /// @author Alexander Neumann &lt;alneuman@techfak.uni-bielefeld.de>
  /// </summary>
  public enum ContentType {
    /// <summary>
    //// no content type specified; should not be used actively
    /// </summary>
    [pbr::OriginalName("CONTENT_UNKNOWN")] ContentUnknown = 0,
    /// <summary>
    //// shows 2-D images
    /// </summary>
    [pbr::OriginalName("CONTENT_IMAGE")] ContentImage = 1,
    /// <summary>
    //// shows videos
    /// </summary>
    [pbr::OriginalName("CONTENT_VIDEO")] ContentVideo = 2,
    /// <summary>
    //// shows instructions in text form; is also used to generate speech output if ssml is not defined
    /// </summary>
    [pbr::OriginalName("CONTENT_TEXT")] ContentText = 3,
    /// <summary>
    //// plays audio (e.g. background music)
    /// </summary>
    [pbr::OriginalName("CONTENT_AUDIO")] ContentAudio = 4,
    /// <summary>
    //// shows images or holograms situated in space
    /// </summary>
    [pbr::OriginalName("CONTENT_VISUAL")] ContentVisual = 5,
    /// <summary>
    //// will be opened with the default OS application
    /// </summary>
    [pbr::OriginalName("CONTENT_EXTERNAL")] ContentExternal = 6,
    /// <summary>
    //// is used for enhanced tts output
    /// </summary>
    [pbr::OriginalName("CONTENT_SSML")] ContentSsml = 7,
  }

  #endregion

}

#endregion Designer generated code
