// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/generic/logger_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avikom.Types.Generic {

  /// <summary>Holder for reflection information generated from avikom/generic/logger_service.proto</summary>
  public static partial class LoggerServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for avikom/generic/logger_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoggerServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNhdmlrb20vZ2VuZXJpYy9sb2dnZXJfc2VydmljZS5wcm90bxIOYXZpa29t",
            "LmdlbmVyaWMaG2F2aWtvbS9nZW5lcmljL3Jlc3VsdC5wcm90bxocZ29vZ2xl",
            "L2FwaS9hbm5vdGF0aW9ucy5wcm90byJTCgdNZXNzYWdlEicKBWxldmVsGAEg",
            "ASgOMhguYXZpa29tLmdlbmVyaWMuTG9nTGV2ZWwSDwoHY29udGVudBgCIAEo",
            "CRIOCgZvcmlnaW4YAyABKAkqPwoITG9nTGV2ZWwSCQoFREVCVUcQABIICgRJ",
            "TkZPEAESCAoEV0FSThACEgkKBUVSUk9SEAMSCQoFRkFUQUwQBDKVAQoNTG9n",
            "Z2VyU2VydmljZRKDAQoDTG9nEhcuYXZpa29tLmdlbmVyaWMuTWVzc2FnZRoW",
            "LmF2aWtvbS5nZW5lcmljLlJlc3VsdCJLgtPkkwJFIgovdjEvbG9nZ2VyOgEq",
            "WhUiEy92MS9sb2dnZXIve29yaWdpbn1aHSIbL3YxL2xvZ2dlci97b3JpZ2lu",
            "fS97bGV2ZWx9QmwKGGFwcC5hdmlrb20udHlwZXMuZ2VuZXJpY1o5Z2l0bGFi",
            "LnViLnVuaS1iaWVsZWZlbGQuZGUvYXZpa29tL2dvLXR5cGVzL2F2aWtvbS9n",
            "ZW5lcmljqgIUQXZpa29tLlR5cGVzLkdlbmVyaWNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Avikom.Types.Generic.ResultReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Avikom.Types.Generic.LogLevel), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Avikom.Types.Generic.Message), global::Avikom.Types.Generic.Message.Parser, new[]{ "Level", "Content", "Origin" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///
  /// The LogLevel specifies the criticality of a log
  /// @author Alexander Neumann &lt;alneuman@techfak.uni-bielefeld.de>
  /// </summary>
  public enum LogLevel {
    /// <summary>
    //// default level used for debugging
    /// </summary>
    [pbr::OriginalName("DEBUG")] Debug = 0,
    /// <summary>
    //// information that might be of interest to developers also during production
    /// </summary>
    [pbr::OriginalName("INFO")] Info = 1,
    /// <summary>
    //// warnings that should be of interest to developers and can foreshadow future errors 
    /// </summary>
    [pbr::OriginalName("WARN")] Warn = 2,
    /// <summary>
    //// errors that are of interest to developers and break functionality
    /// </summary>
    [pbr::OriginalName("ERROR")] Error = 3,
    /// <summary>
    //// erros that result in total or partial system failure
    /// </summary>
    [pbr::OriginalName("FATAL")] Fatal = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  ///
  /// A message specifying the log combining the log level, the logging message and the origin
  /// @author Alexander Neumann &lt;alneuman@techfak.uni-bielefeld.de>
  /// </summary>
  public sealed partial class Message : pb::IMessage<Message> {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avikom.Types.Generic.LoggerServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Message(Message other) : this() {
      level_ = other.level_;
      content_ = other.content_;
      origin_ = other.origin_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 1;
    private global::Avikom.Types.Generic.LogLevel level_ = 0;
    /// <summary>
    //// holds the log level of the message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Avikom.Types.Generic.LogLevel Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 2;
    private string content_ = "";
    /// <summary>
    //// holds the log message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "origin" field.</summary>
    public const int OriginFieldNumber = 3;
    private string origin_ = "";
    /// <summary>
    //// which service issued the log
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Origin {
      get { return origin_; }
      set {
        origin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Level != other.Level) return false;
      if (Content != other.Content) return false;
      if (Origin != other.Origin) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (Origin.Length != 0) hash ^= Origin.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Level != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Level);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Content);
      }
      if (Origin.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Origin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Level);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (Origin.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Origin);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.Origin.Length != 0) {
        Origin = other.Origin;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Level = (global::Avikom.Types.Generic.LogLevel) input.ReadEnum();
            break;
          }
          case 18: {
            Content = input.ReadString();
            break;
          }
          case 26: {
            Origin = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
