// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/generic/user_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avikom.Types.Generic {

  /// <summary>Holder for reflection information generated from avikom/generic/user_service.proto</summary>
  public static partial class UserServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for avikom/generic/user_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFhdmlrb20vZ2VuZXJpYy91c2VyX3NlcnZpY2UucHJvdG8SDmF2aWtvbS5n",
            "ZW5lcmljGhlhdmlrb20vZ2VuZXJpYy91c2VyLnByb3RvGiFhdmlrb20vZ2Vu",
            "ZXJpYy91c2VyX3Byb2ZpbGUucHJvdG8aHGdvb2dsZS9hcGkvYW5ub3RhdGlv",
            "bnMucHJvdG8ygAQKC1VzZXJTZXJ2aWNlEsUBCgdHZXRJbmZvEhQuYXZpa29t",
            "LmdlbmVyaWMuVXNlchoULmF2aWtvbS5nZW5lcmljLlVzZXIijQGC0+STAoYB",
            "EhEvdjEvdXNlcnMvaWQve2lkfVojEiEvdjEvdXNlcnMvZmlyc3RfbmFtZS97",
            "Zmlyc3RfbmFtZX1aIRIfL3YxL3VzZXJzL2xhc3RfbmFtZS97bGFzdF9uYW1l",
            "fVopEicvdjEvdXNlcnMvbmFtZS97Zmlyc3RfbmFtZX0ve2xhc3RfbmFtZX0S",
            "2wEKCkdldFByb2ZpbGUSFC5hdmlrb20uZ2VuZXJpYy5Vc2VyGhsuYXZpa29t",
            "LmdlbmVyaWMuVXNlclByb2ZpbGUimQGC0+STApIBEhQvdjEvcHJvZmlsZXMv",
            "aWQve2lkfVomEiQvdjEvcHJvZmlsZXMvZmlyc3RfbmFtZS97Zmlyc3RfbmFt",
            "ZX1aJBIiL3YxL3Byb2ZpbGVzL2xhc3RfbmFtZS97bGFzdF9uYW1lfVosEiov",
            "djEvcHJvZmlsZXMvbmFtZS97Zmlyc3RfbmFtZX0ve2xhc3RfbmFtZX0SSwoH",
            "QWRkVXNlchIULmF2aWtvbS5nZW5lcmljLlVzZXIaFC5hdmlrb20uZ2VuZXJp",
            "Yy5Vc2VyIhSC0+STAg4iCS92MS91c2VyczoBKkJsChhhcHAuYXZpa29tLnR5",
            "cGVzLmdlbmVyaWNaOWdpdGxhYi51Yi51bmktYmllbGVmZWxkLmRlL2F2aWtv",
            "bS9nby10eXBlcy9hdmlrb20vZ2VuZXJpY6oCFEF2aWtvbS5UeXBlcy5HZW5l",
            "cmljYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Avikom.Types.Generic.UserReflection.Descriptor, global::Avikom.Types.Generic.UserProfileReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
