#!/usr/bin/env python

from protoc_base_plugin.parser import ParserBase, indent, plugin
from protoc_base_plugin.generators.json_parser import JsonParser


def main():
    JsonParser(comments=True, options=True).parse()


if __name__ == "__main__":
    main()
