// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/tracking/location_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Avikom.Types.Tracking {
  /// <summary>
  ///*
  /// This services provides the scene location of an object either absolute to the scene's origin or relative to another entity (e.g. the user).
  /// @author: Alexander Neumann &lt;alneuman@techfak.uni-bielefeld.de>
  /// </summary>
  public static partial class LocationService
  {
    static readonly string __ServiceName = "avikom.tracking.LocationService";

    static readonly grpc::Marshaller<global::Avikom.Types.Tracking.TargetRequest> __Marshaller_avikom_tracking_TargetRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Avikom.Types.Tracking.TargetRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Avikom.Types.Math.Vector3D> __Marshaller_avikom_math_Vector3D = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Avikom.Types.Math.Vector3D.Parser.ParseFrom);

    static readonly grpc::Method<global::Avikom.Types.Tracking.TargetRequest, global::Avikom.Types.Math.Vector3D> __Method_GetScenePosition = new grpc::Method<global::Avikom.Types.Tracking.TargetRequest, global::Avikom.Types.Math.Vector3D>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetScenePosition",
        __Marshaller_avikom_tracking_TargetRequest,
        __Marshaller_avikom_math_Vector3D);

    static readonly grpc::Method<global::Avikom.Types.Tracking.TargetRequest, global::Avikom.Types.Math.Vector3D> __Method_GetRelativePosition = new grpc::Method<global::Avikom.Types.Tracking.TargetRequest, global::Avikom.Types.Math.Vector3D>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetRelativePosition",
        __Marshaller_avikom_tracking_TargetRequest,
        __Marshaller_avikom_math_Vector3D);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Avikom.Types.Tracking.LocationServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LocationService</summary>
    [grpc::BindServiceMethod(typeof(LocationService), "BindService")]
    public abstract partial class LocationServiceBase
    {
      /// <summary>
      //// returns the absolute position of an object relative to the scenes origin
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      public virtual global::System.Threading.Tasks.Task GetScenePosition(global::Avikom.Types.Tracking.TargetRequest request, grpc::IServerStreamWriter<global::Avikom.Types.Math.Vector3D> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      //// returns the  position of an object relative to the object/entity mentioned in `TargetRequest`
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      public virtual global::System.Threading.Tasks.Task GetRelativePosition(global::Avikom.Types.Tracking.TargetRequest request, grpc::IServerStreamWriter<global::Avikom.Types.Math.Vector3D> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LocationService</summary>
    public partial class LocationServiceClient : grpc::ClientBase<LocationServiceClient>
    {
      /// <summary>Creates a new client for LocationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public LocationServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LocationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LocationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected LocationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected LocationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      //// returns the absolute position of an object relative to the scenes origin
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::Avikom.Types.Math.Vector3D> GetScenePosition(global::Avikom.Types.Tracking.TargetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetScenePosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      //// returns the absolute position of an object relative to the scenes origin
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::Avikom.Types.Math.Vector3D> GetScenePosition(global::Avikom.Types.Tracking.TargetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetScenePosition, null, options, request);
      }
      /// <summary>
      //// returns the  position of an object relative to the object/entity mentioned in `TargetRequest`
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::Avikom.Types.Math.Vector3D> GetRelativePosition(global::Avikom.Types.Tracking.TargetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRelativePosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      //// returns the  position of an object relative to the object/entity mentioned in `TargetRequest`
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::Avikom.Types.Math.Vector3D> GetRelativePosition(global::Avikom.Types.Tracking.TargetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetRelativePosition, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override LocationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LocationServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(LocationServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetScenePosition, serviceImpl.GetScenePosition)
          .AddMethod(__Method_GetRelativePosition, serviceImpl.GetRelativePosition).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LocationServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetScenePosition, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Avikom.Types.Tracking.TargetRequest, global::Avikom.Types.Math.Vector3D>(serviceImpl.GetScenePosition));
      serviceBinder.AddMethod(__Method_GetRelativePosition, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Avikom.Types.Tracking.TargetRequest, global::Avikom.Types.Math.Vector3D>(serviceImpl.GetRelativePosition));
    }

  }
}
#endregion
