// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/assistance/issue_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Avikom.Types.Assistance {
  /// <summary>
  ///*
  /// This service manages issues. It should also communicate with `IssueStorageService` behind the scene for persisten issue management.
  /// @author Alexander Neumann &lt;alneuman@techfak.uni-bielefeld.de>
  /// </summary>
  public static partial class IssueService
  {
    static readonly string __ServiceName = "avikom.assistance.IssueService";

    static readonly grpc::Marshaller<global::Avikom.Types.Assistance.IssueQuery> __Marshaller_avikom_assistance_IssueQuery = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Avikom.Types.Assistance.IssueQuery.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Avikom.Types.Generic.Result> __Marshaller_avikom_generic_Result = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Avikom.Types.Generic.Result.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Avikom.Types.Assistance.IssueList> __Marshaller_avikom_assistance_IssueList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Avikom.Types.Assistance.IssueList.Parser.ParseFrom);

    static readonly grpc::Method<global::Avikom.Types.Assistance.IssueQuery, global::Avikom.Types.Generic.Result> __Method_StartIssue = new grpc::Method<global::Avikom.Types.Assistance.IssueQuery, global::Avikom.Types.Generic.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartIssue",
        __Marshaller_avikom_assistance_IssueQuery,
        __Marshaller_avikom_generic_Result);

    static readonly grpc::Method<global::Avikom.Types.Assistance.IssueQuery, global::Avikom.Types.Assistance.IssueList> __Method_GetIssue = new grpc::Method<global::Avikom.Types.Assistance.IssueQuery, global::Avikom.Types.Assistance.IssueList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetIssue",
        __Marshaller_avikom_assistance_IssueQuery,
        __Marshaller_avikom_assistance_IssueList);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Avikom.Types.Assistance.IssueServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of IssueService</summary>
    [grpc::BindServiceMethod(typeof(IssueService), "BindService")]
    public abstract partial class IssueServiceBase
    {
      /// <summary>
      //// Starts a process for the queried issue.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Avikom.Types.Generic.Result> StartIssue(global::Avikom.Types.Assistance.IssueQuery request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      //// Returns a list of issues filtered by `IssueQuery`.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Avikom.Types.Assistance.IssueList> GetIssue(global::Avikom.Types.Assistance.IssueQuery request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for IssueService</summary>
    public partial class IssueServiceClient : grpc::ClientBase<IssueServiceClient>
    {
      /// <summary>Creates a new client for IssueService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public IssueServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for IssueService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public IssueServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected IssueServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected IssueServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      //// Starts a process for the queried issue.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Avikom.Types.Generic.Result StartIssue(global::Avikom.Types.Assistance.IssueQuery request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartIssue(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      //// Starts a process for the queried issue.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Avikom.Types.Generic.Result StartIssue(global::Avikom.Types.Assistance.IssueQuery request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StartIssue, null, options, request);
      }
      /// <summary>
      //// Starts a process for the queried issue.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Avikom.Types.Generic.Result> StartIssueAsync(global::Avikom.Types.Assistance.IssueQuery request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartIssueAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      //// Starts a process for the queried issue.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Avikom.Types.Generic.Result> StartIssueAsync(global::Avikom.Types.Assistance.IssueQuery request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StartIssue, null, options, request);
      }
      /// <summary>
      //// Returns a list of issues filtered by `IssueQuery`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Avikom.Types.Assistance.IssueList GetIssue(global::Avikom.Types.Assistance.IssueQuery request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetIssue(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      //// Returns a list of issues filtered by `IssueQuery`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Avikom.Types.Assistance.IssueList GetIssue(global::Avikom.Types.Assistance.IssueQuery request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetIssue, null, options, request);
      }
      /// <summary>
      //// Returns a list of issues filtered by `IssueQuery`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Avikom.Types.Assistance.IssueList> GetIssueAsync(global::Avikom.Types.Assistance.IssueQuery request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetIssueAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      //// Returns a list of issues filtered by `IssueQuery`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Avikom.Types.Assistance.IssueList> GetIssueAsync(global::Avikom.Types.Assistance.IssueQuery request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetIssue, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override IssueServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IssueServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(IssueServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_StartIssue, serviceImpl.StartIssue)
          .AddMethod(__Method_GetIssue, serviceImpl.GetIssue).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, IssueServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_StartIssue, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Avikom.Types.Assistance.IssueQuery, global::Avikom.Types.Generic.Result>(serviceImpl.StartIssue));
      serviceBinder.AddMethod(__Method_GetIssue, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Avikom.Types.Assistance.IssueQuery, global::Avikom.Types.Assistance.IssueList>(serviceImpl.GetIssue));
    }

  }
}
#endregion
