// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avikom/assistance/task_stereotype.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Avikom.Types.Assistance {

  /// <summary>Holder for reflection information generated from avikom/assistance/task_stereotype.proto</summary>
  public static partial class TaskStereotypeReflection {

    #region Descriptor
    /// <summary>File descriptor for avikom/assistance/task_stereotype.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaskStereotypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cidhdmlrb20vYXNzaXN0YW5jZS90YXNrX3N0ZXJlb3R5cGUucHJvdG8SEWF2",
            "aWtvbS5hc3Npc3RhbmNlGi1hdmlrb20vYXNzaXN0YW5jZS9zZXJ2aWNlX2Nv",
            "bmZpZ3VyYXRpb24ucHJvdG8aJmF2aWtvbS9hc3Npc3RhbmNlL2Nob2ljZXNf",
            "Y29uZmlnLnByb3RvGihhdmlrb20vYXNzaXN0YW5jZS9hc3Npc3RhbmNlX2xl",
            "dmVsLnByb3RvGh5hdmlrb20vdW5pdHkvZ2FtZV9vYmplY3QucHJvdG8i6AIK",
            "DlRhc2tTdGVyZW90eXBlEjsKCGNhdGVnb3J5GAEgASgOMikuYXZpa29tLmFz",
            "c2lzdGFuY2UuVGFza1N0ZXJlb3R5cGVDYXRlZ29yeRIxCgdjaG9pY2VzGAUg",
            "ASgLMiAuYXZpa29tLmFzc2lzdGFuY2UuQ2hvaWNlc0NvbmZpZxIOCgZ0YXJn",
            "ZXQYBiABKAkSOQoIc2VydmljZXMYByADKAsyJy5hdmlrb20uYXNzaXN0YW5j",
            "ZS5TZXJ2aWNlQ29uZmlndXJhdGlvbhI+ChJkZWZhdWx0X2Fzc2lzdGFuY2UY",
            "CiABKA4yIi5hdmlrb20uYXNzaXN0YW5jZS5Bc3Npc3RhbmNlTGV2ZWwSPgoS",
            "bWluaW1hbF9hc3Npc3RhbmNlGAsgASgOMiIuYXZpa29tLmFzc2lzdGFuY2Uu",
            "QXNzaXN0YW5jZUxldmVsEhsKE2Fzc2lzdGFuY2VfZGVjcmVhc2UYDCABKAIq",
            "pAEKFlRhc2tTdGVyZW90eXBlQ2F0ZWdvcnkSDwoLVEFTS19VTktPV04QABIQ",
            "CgxUQVNLX1BFTkRJTkcQARIRCg1UQVNLX0RFQ0lTSU9OEAISDwoLVEFTS19B",
            "U1NJR04QAxIOCgpUQVNLX0dVSURFEAQSEAoMVEFTS19BUFBST1ZFEAUSDgoK",
            "VEFTS19JTlBVVBAGEhEKDVRBU0tfSU5URVJOQUwQB0J1ChthcHAuYXZpa29t",
            "LnR5cGVzLmFzc2lzdGFuY2VaPGdpdGxhYi51Yi51bmktYmllbGVmZWxkLmRl",
            "L2F2aWtvbS9nby10eXBlcy9hdmlrb20vYXNzaXN0YW5jZaoCF0F2aWtvbS5U",
            "eXBlcy5Bc3Npc3RhbmNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Avikom.Types.Assistance.ServiceConfigurationReflection.Descriptor, global::Avikom.Types.Assistance.ChoicesConfigReflection.Descriptor, global::Avikom.Types.Assistance.AssistanceLevelReflection.Descriptor, global::Avikom.Types.Unity.GameObjectReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Avikom.Types.Assistance.TaskStereotypeCategory), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Avikom.Types.Assistance.TaskStereotype), global::Avikom.Types.Assistance.TaskStereotype.Parser, new[]{ "Category", "Choices", "Target", "Services", "DefaultAssistance", "MinimalAssistance", "AssistanceDecrease" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TaskStereotypeCategory {
    /// <summary>
    //// default value; should not be used actively
    /// </summary>
    [pbr::OriginalName("TASK_UNKOWN")] TaskUnkown = 0,
    /// <summary>
    //// waiting for user/peer to finish task, a failure needs to be raised if impossible
    /// </summary>
    [pbr::OriginalName("TASK_PENDING")] TaskPending = 1,
    /// <summary>
    //// chose answer out of 'choices'
    /// </summary>
    [pbr::OriginalName("TASK_DECISION")] TaskDecision = 2,
    /// <summary>
    //// assign a 'target'
    /// </summary>
    [pbr::OriginalName("TASK_ASSIGN")] TaskAssign = 3,
    /// <summary>
    //// guide user to a 'target'
    /// </summary>
    [pbr::OriginalName("TASK_GUIDE")] TaskGuide = 4,
    /// <summary>
    //// can be approved or declined, simple yes no question
    /// </summary>
    [pbr::OriginalName("TASK_APPROVE")] TaskApprove = 5,
    /// <summary>
    //// user needs to provide further information; multiple input 'services' might be provided;
    /// </summary>
    [pbr::OriginalName("TASK_INPUT")] TaskInput = 6,
    /// <summary>
    //// informs users/peers about ongoing processes; should not be used for critical information; might not be perceivable by the user
    /// </summary>
    [pbr::OriginalName("TASK_INTERNAL")] TaskInternal = 7,
  }

  #endregion

  #region Messages
  /// <summary>
  ///*
  /// This messages classifies the assistance mechanism needed for a `TaskStep`.
  /// Paramaters may contain variable names in `{curly brackets}`.
  /// These should be resolved during runtime with the session's variable content.
  /// @author: Alexander Neumann &lt;alneuman@techfak.uni-bielefeld.de>
  /// </summary>
  public sealed partial class TaskStereotype : pb::IMessage<TaskStereotype> {
    private static readonly pb::MessageParser<TaskStereotype> _parser = new pb::MessageParser<TaskStereotype>(() => new TaskStereotype());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TaskStereotype> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Avikom.Types.Assistance.TaskStereotypeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TaskStereotype() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TaskStereotype(TaskStereotype other) : this() {
      category_ = other.category_;
      choices_ = other.choices_ != null ? other.choices_.Clone() : null;
      target_ = other.target_;
      services_ = other.services_.Clone();
      defaultAssistance_ = other.defaultAssistance_;
      minimalAssistance_ = other.minimalAssistance_;
      assistanceDecrease_ = other.assistanceDecrease_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TaskStereotype Clone() {
      return new TaskStereotype(this);
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 1;
    private global::Avikom.Types.Assistance.TaskStereotypeCategory category_ = 0;
    /// <summary>
    //// defines the kind of action a user can conduct to process this task
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Avikom.Types.Assistance.TaskStereotypeCategory Category {
      get { return category_; }
      set {
        category_ = value;
      }
    }

    /// <summary>Field number for the "choices" field.</summary>
    public const int ChoicesFieldNumber = 5;
    private global::Avikom.Types.Assistance.ChoicesConfig choices_;
    /// <summary>
    //// a set of choices a user can choose; will be only be considered for tasks where decisions have to be made
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Avikom.Types.Assistance.ChoicesConfig Choices {
      get { return choices_; }
      set {
        choices_ = value;
      }
    }

    /// <summary>Field number for the "target" field.</summary>
    public const int TargetFieldNumber = 6;
    private string target_ = "";
    /// <summary>
    //// the name of a  virtual or real object of central importance for that task (e.g. the target location during guidance)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Target {
      get { return target_; }
      set {
        target_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "services" field.</summary>
    public const int ServicesFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Avikom.Types.Assistance.ServiceConfiguration> _repeated_services_codec
        = pb::FieldCodec.ForMessage(58, global::Avikom.Types.Assistance.ServiceConfiguration.Parser);
    private readonly pbc::RepeatedField<global::Avikom.Types.Assistance.ServiceConfiguration> services_ = new pbc::RepeatedField<global::Avikom.Types.Assistance.ServiceConfiguration>();
    /// <summary>
    //// a set of services that can be used to solve that task
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Avikom.Types.Assistance.ServiceConfiguration> Services {
      get { return services_; }
    }

    /// <summary>Field number for the "default_assistance" field.</summary>
    public const int DefaultAssistanceFieldNumber = 10;
    private global::Avikom.Types.Assistance.AssistanceLevel defaultAssistance_ = 0;
    /// <summary>
    //// the default assistance for this step if no step proficiency is available
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Avikom.Types.Assistance.AssistanceLevel DefaultAssistance {
      get { return defaultAssistance_; }
      set {
        defaultAssistance_ = value;
      }
    }

    /// <summary>Field number for the "minimal_assistance" field.</summary>
    public const int MinimalAssistanceFieldNumber = 11;
    private global::Avikom.Types.Assistance.AssistanceLevel minimalAssistance_ = 0;
    /// <summary>
    //// overrides the category-induced minimal assistance levels but cannot be lower
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Avikom.Types.Assistance.AssistanceLevel MinimalAssistance {
      get { return minimalAssistance_; }
      set {
        minimalAssistance_ = value;
      }
    }

    /// <summary>Field number for the "assistance_decrease" field.</summary>
    public const int AssistanceDecreaseFieldNumber = 12;
    private float assistanceDecrease_;
    /// <summary>
    //// factor to reduce `tendency` when a task was conducted successfully, this will be combined with user preferences; 0 is considered unset and will be ignored
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float AssistanceDecrease {
      get { return assistanceDecrease_; }
      set {
        assistanceDecrease_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TaskStereotype);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TaskStereotype other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Category != other.Category) return false;
      if (!object.Equals(Choices, other.Choices)) return false;
      if (Target != other.Target) return false;
      if(!services_.Equals(other.services_)) return false;
      if (DefaultAssistance != other.DefaultAssistance) return false;
      if (MinimalAssistance != other.MinimalAssistance) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AssistanceDecrease, other.AssistanceDecrease)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Category != 0) hash ^= Category.GetHashCode();
      if (choices_ != null) hash ^= Choices.GetHashCode();
      if (Target.Length != 0) hash ^= Target.GetHashCode();
      hash ^= services_.GetHashCode();
      if (DefaultAssistance != 0) hash ^= DefaultAssistance.GetHashCode();
      if (MinimalAssistance != 0) hash ^= MinimalAssistance.GetHashCode();
      if (AssistanceDecrease != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AssistanceDecrease);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Category != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Category);
      }
      if (choices_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Choices);
      }
      if (Target.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Target);
      }
      services_.WriteTo(output, _repeated_services_codec);
      if (DefaultAssistance != 0) {
        output.WriteRawTag(80);
        output.WriteEnum((int) DefaultAssistance);
      }
      if (MinimalAssistance != 0) {
        output.WriteRawTag(88);
        output.WriteEnum((int) MinimalAssistance);
      }
      if (AssistanceDecrease != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(AssistanceDecrease);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Category != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Category);
      }
      if (choices_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Choices);
      }
      if (Target.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Target);
      }
      size += services_.CalculateSize(_repeated_services_codec);
      if (DefaultAssistance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DefaultAssistance);
      }
      if (MinimalAssistance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MinimalAssistance);
      }
      if (AssistanceDecrease != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TaskStereotype other) {
      if (other == null) {
        return;
      }
      if (other.Category != 0) {
        Category = other.Category;
      }
      if (other.choices_ != null) {
        if (choices_ == null) {
          Choices = new global::Avikom.Types.Assistance.ChoicesConfig();
        }
        Choices.MergeFrom(other.Choices);
      }
      if (other.Target.Length != 0) {
        Target = other.Target;
      }
      services_.Add(other.services_);
      if (other.DefaultAssistance != 0) {
        DefaultAssistance = other.DefaultAssistance;
      }
      if (other.MinimalAssistance != 0) {
        MinimalAssistance = other.MinimalAssistance;
      }
      if (other.AssistanceDecrease != 0F) {
        AssistanceDecrease = other.AssistanceDecrease;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Category = (global::Avikom.Types.Assistance.TaskStereotypeCategory) input.ReadEnum();
            break;
          }
          case 42: {
            if (choices_ == null) {
              Choices = new global::Avikom.Types.Assistance.ChoicesConfig();
            }
            input.ReadMessage(Choices);
            break;
          }
          case 50: {
            Target = input.ReadString();
            break;
          }
          case 58: {
            services_.AddEntriesFrom(input, _repeated_services_codec);
            break;
          }
          case 80: {
            DefaultAssistance = (global::Avikom.Types.Assistance.AssistanceLevel) input.ReadEnum();
            break;
          }
          case 88: {
            MinimalAssistance = (global::Avikom.Types.Assistance.AssistanceLevel) input.ReadEnum();
            break;
          }
          case 101: {
            AssistanceDecrease = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
