name: Publish avikom-unity-types
on:
  release:
    types: [created]
  push:
    branches:
      - dev-gha
      - dev-gha-unity
jobs:
  publish-unity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/checkout@v4
        with:
          path: generated/unity
          ref: upm
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup dotnet 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
      - name: Generate tagged version
        if: startsWith(github.ref, 'refs/tags')
        run: make unity
        env:
          VERSION: ${{ github.ref_name }}
          EMAIL: github-actions[bot]@users.noreply.github.com
          USER: github-actions[bot]
      - name: Generate test version
        if: "!startsWith(github.ref, 'refs/tags')"
        run: make unity
        env:
          VERSION: 0.10.0-dev${{ github.run_number }}
          EMAIL: github-actions[bot]@users.noreply.github.com
          USER: github-actions[bot]
