name: Publish app.avikom.types
on:
  release:
    types: [created]
  push:
    branches:
      - dev-gha
      - dev-gha-java
jobs:
  publish-java:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate and package
        run: make java
        env:
          VERSION: ${{ github.ref_name }}
      - name: Publish package
        run: make java_publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
