name: Publish app.avikom.types 
on:
  release:
    types: [created]
  push:
    branches:
      - dev-gha

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Prepare workspace
        run: cp -r templates/java workspace
      - name: Configure version
        run: sed -i "s/@VERSION@/${VERSION}/g" workspace/pom.xml
      - name: Build and publish package
        run: mvn --batch-mode deploy
        working-directory: workspace
        env:
          VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
